### ISSUE TITLE
kotlinx-cli is effectively unmaintained

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/vaadin-boot#25]
kotlinx-cli](https://github.com/Kotlin/kotlinx-cli

This library is obsolete
It is effectively unmaintained. Please consider using other libraries.

**Comment by mvysny** [comment]
Thanks! kotlinx-cli was present only temporarily - I thought I could control vaadin-boot via cmdline but every app needs are different, so the idea was ultimately scrapped. Please see #12 for more details. Therefore, there should be no dependency on kotlinx-cli - if there is, please let me know where exactly it's pulled in, so that I can remove it.

**Comment by mvysny** [comment]
The kotlinx-cli has been removed from the project, closing this ticket as won't fix.
